### ISSUE TITLE
Unable to test code refactoring when given place reports more than one available refactoring

### ISSUE THREAD

**Issue by cezarypiatek** [phoenix172/RoslynNUnitLight.NetStandard#2]
I'd like to test application of given refactoring providers even if given place reports more than one available refactoring.  If there is more than one  available refactoring options, the `TestCodeRefactoring` method should accept the index of refactoring that should be applied. Similar approach was used in the default assertion method for code analyzers that ships with Roslyn analyzer template.

**Comment by phoenix172** [comment]
Merged into repository and published new package(1.2.4). It should be up shortly. Thanks for the contribution.

**Comment by cezarypiatek** [comment]
Thanks for accepting PR.
